### ISSUE TITLE
Project root

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#13]
I'm missing the root attribute on the project; `project.getRoot()`

**Comment by mkolar** [comment]
Ah. yes we should add that.

**Comment by tokejepsen** [comment]
How does 'root' sound for data member in the project dictionary? Or 'directory'?

**Comment by mkolar** [comment]
I'd keep it as root. That is what ftrack is calling it to if I'm not mistaken

**Comment by tokejepsen** [comment]
Seems to be a difference between `project.getRoot()` and `project.get('root')`, where they return a disk path and directory name respectively;

```
the_call_up_00897
Y:\projects\the_call_up_00897
```

**Comment by mkolar** [comment]
I'm getting identical result when I run both on a project. Full path

**Comment by mottosso** [comment]
It might depend on what your current directory is.

Check against this.

``` python
import os
print os.getcwd()
```

If it's `Y:\projects`, then it might get trimmed away.

**Comment by tokejepsen** [comment]
> I'm getting identical result when I run both on a project. Full path

Are you using disks in ftrack? or is your project folder the full path?

**Comment by mkolar** [comment]
Yep my project folder is a full path. I have discs set up, but not really using them. I'll slowly be switching to the new API and locations and disks should be irrelevant there.

**Comment by tokejepsen** [comment]
Cool, I'll use `project.getRoot()` and put it into `project['root']`.

**Comment by mkolar** [comment]
The new seems to be completely getting rid of the getRoot and other convenience function in favor of simply querying keys. So I'd say starting to use project.get('root') might be easier to port later on. It would just change to project['root']

**Comment by tokejepsen** [comment]
> So I'd say starting to use project.get('root') might be easier to port later on. It would just change to project['root']

Think I'll use `project.getRoot()` as this returns a full path here, and at yours.

**Comment by mkolar** [comment]
OK. whatever works.

**Comment by mottosso** [comment]
Out of curiosity, what does the `getRoot` implementation look like? Could you post it here?

``` python
import inspect
print inspect.getsource(getRoot)
```

**Comment by tokejepsen** [comment]
> Out of curiosity, what does the getRoot implementation look like? Could you post it here?

Don't know. Its part of the ftrack api.

**Comment by mkolar** [comment]
> Out of curiosity, what does the getRoot implementation look like? Could you post it here?

``` python
def getRoot(self):
        return self.getPath()

def getPath(self,full=False):
        """
        Get OS specific path to project folder

        :param full: ``bool`` Include asset prefix setting at end of path
        :rtype: A string with the file path to the project
         """     
        data = {'type':'path','showid':self.getId(),'full':full}
        response = xmlServer.action('get',data)
        return response
```

Of course it keeps nesting down through xml server module etc. Don't really feel like tracking it donw fully :)

**Comment by mottosso** [comment]
> Of course it keeps nesting down through xml server module etc.

Ah, okay, I was thinking it was using something like `os.path.realpath` or similar some where, which might explain why one was relative and the other absolute. Nevermind, but thanks for digging it up. :)

Totally off topic, but out of interest, is `xmlServer` something you are familiar with elsewhere in the ftrack API?

**Comment by mkolar** [comment]
It's used throughout the api, but not a public part of it. I noticed it being called quite a bit throughout. But I only had a quick glance at it.

**Comment by mottosso** [comment]
Is the API source on GitHub or something so I could have a look?

**Comment by mkolar** [comment]
You can see the full code and docs for it in [ftrack docs](http://ftrack.rtd.ftrack.com/en/latest/developing/api_reference/index.html), They will be changing the api soon though for a more flexible and powerful one. I'm testing it now and it's very different from current api

**Comment by mottosso** [comment]
The new API, is it this you think?
- https://bitbucket.org/ftrack/ftrack-python-api

**Comment by mkolar** [comment]
Indeed
