### ISSUE TITLE
Merge all validators into 1 vaildator and 1 extractor

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#17]
The validator will validate asset, asset_version and component.
If component already exists, issue warning and nothing else.

The extractor will create any missing item.

**Comment by tokejepsen** [comment]
> If component already exists, issue warning and nothing else.

I'm still unsure about only issueing a warning about this. As it is something that is potentially breaking, I would like it to be fixed as we go along, similar to all other validators function; flag a problem to fix.

@mkolar, you main problem is that you don't know the final output path until its extracted, but how come you can't predict it? Code duplication?

**Comment by mkolar** [comment]
> but how come you can't predict it?

Because to predict it I would have to do conforming work in selector or validator. Let's pick playblast as example, which get's saved to disk somewhere (next to a workfile for instance), this isn't the file I want to be putting into ftrack database. It's the one I get after conforming it to it's correct location. 

Of course this path could theoretically determined in selection for example, But then the conforming step becomes absolutely unnecessary. 

In general if keeping to SVEC workflow the way I understand it. You have no way of knowing the final location of the file until the conforming step, unless you do all the heavy lifting of determing a final path in selection and then just do the actual file moving in the conform.

**Comment by mkolar** [comment]
How is it breaking however? If you try to create component that already exists in ftrack, if fairly gracefully fails and tells you you aren't allowed. This seem to be working very well for us right now. 

[conform_ftrack_component](https://github.com/mkolar/pyblish-ftrack/blob/master/pyblish_ftrack/plugins/conform_ftrack_component.py)
[validate_ftrack_component](https://github.com/mkolar/pyblish-ftrack/blob/master/pyblish_ftrack/plugins/validate_ftrack_component.py)

**Comment by tokejepsen** [comment]
> How is it breaking however?

If the component exists, which it does most of the time for us as we are resubmitting a version to render until the artist is happy for it to progress to a supervisor, and the paths are different, the component won't be updated. Unless we overwrite which we don't want to do by default.

Are you creating a new version every time an artist submits something like a render?

**Comment by mottosso** [comment]
> In general if keeping to SVEC workflow the way I understand it. You have no way of knowing the final location of the file until the conforming step, 

That's right. In short, you shouldn't _need_ to know the final destination until Conform. I can see how incrementing a version contradicts this however, as you will need to know about previous versions to do figure out the next (assuming that is what we're talking about?).

It sounds like the more important question then becomes "should any plug-in depend on whether a version already exists?".

In the simplest case, a publish could always increment. SVEC assumes that published data is immutable and that a publish is idempotent.

**Comment by tokejepsen** [comment]
> In the simplest case, a publish could always increment. SVEC assumes that published data is immutable and that a publish is idempotent.

Would you expect to overwrite data?

**Comment by mkolar** [comment]
I'm a bit lost. Artist is sending his compositing to farm over and over as the same version, rewriting the renders until he is happy with it right? Then he changes the status to supervisor review once he is. Are you versioning these outputs?

The way we work is that people do their own previews and only publish when they want supervisor to see it. No personal versions in ftrack. ever

**Comment by mottosso** [comment]
> Would you expect to overwrite data?

No, that is what I meant with immutable. Nothing published ever changes.

**Comment by mottosso** [comment]
> Artist is sending his compositing to farm over and over as the save version, rewriting the renders until he is happy with it right? Then he changes the status to supervisor review once he is. Are you versioning these outputs?

Ah, looks like we found the issue.

Yes, this is unorthodox. If space is your concern, then grabage collection can help. If updating to a newer version is your concern, then an asset library can help.

You can of course do this still, but I think it's important to know it isn't SVEC and that you might have to bend some rules.

**Comment by tokejepsen** [comment]
So the setup we have is that artists rewrites the data, renders and published scenes, until they are happy with the result. They then send this off to the supervisor, when this comes back from the supervisor, the scene gets versioned up so the artist works a new version.

The artist can also version up while working on a shot.

The main problem I have been having with components not being the same, is during a transitional phase where new code is introduced. Here its quite useful to get those components flagged.

**Comment by mottosso** [comment]
> So the setup we have is that artists rewrites the data, renders and published scenes, until they are happy with the result. 

That isn't publishing, that's just submitting to a farm. Publishing is _sharing_. Have you guys been publishing as just a way of automating farm submission? :O

**Comment by mkolar** [comment]
By new code you mean, that you start saving outputs somewhere else than was usual until that point? 

If that's so then I'd just make it into a separate validator because that is very workflow specific. And wouldn't apply most of other studios.

**Comment by tokejepsen** [comment]
> If that's so then I'd just make it into a separate validator because that is very workflow specific. And wouldn't apply most of other studios.

That seem like the best solution until the pipeline has stabilized.
