### ISSUE TITLE
Query version in selector

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#20]
Referring to these lines; https://github.com/pyblish/pyblish-ftrack/blob/master/pyblish_ftrack/plugins/select_ftrack_data.py#L68-L87

Was there any special reason for these lines?
As we are moving all validation into one validator, I don't see a need for this in the selector.

**Comment by mkolar** [comment]
Yep that can go into the validator. Or rather get replaced by the validator

**Comment by mottosso** [comment]
When referring to lines, don't forget to make absolute links by pressing "y" in the browser windows. It will replace the browser link with one targeting a file at a certain point in time, so that we can browse to it even after it has been updated.
