### ISSUE TITLE
Asset Type

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#24]
Think we need the option to select an asset type, along with the default behaviour of using the task type.

We can do this similarly to how the current `ftrackAssetName` is working.

**Comment by mkolar** [comment]
I absolutely agree. Was thinking about that for a while now.

**Comment by mkolar** [comment]
However this should probably be done as optional data member. If we find it, we use it, if not, default behavior runs.

**Comment by tokejepsen** [comment]
Yup, same as `ftrackAssetName`

**Comment by mkolar** [comment]
I'm almost done with it now. I'll test and see how it works

**Comment by mkolar** [comment]
done and works nice.
