### ISSUE TITLE
Make select_context_version independent from ftrack

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#25]
I guess ideally this context version selector would be its own repo, but a single plugin doesn't justify it. So to still make use of the version selector, I suggest to putting the `version_get` method into the plugin and make it independent.

**Comment by mkolar** [comment]
> I guess ideally this context version selector would be its own repo, 

I can't agree here. Version is essential information and without it you can't publish to ftrack at all. So it should be handled by the extension somehow. But we can put it into the plugin, that's not a problem

**Comment by mkolar** [comment]
Done this. will merge with next pull request
