### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-ftrack#29]
Hi guys,

I've been having a few conversations with another studio interested in using Pyblish with FTrack and was thinking it would be very helpful to be able to point them to a sort of overview of the schools of thought that went into the current set-up you have been building.

Would it be possible to break it down into perhaps a bullet-list, followed by a short summary of what it would take/mean for anyone to pick this extension up and start using it? I'd be happy to help with structure and formatting, and reading things through and such, but I'm less able in the technical aspects of actually getting this up and running.

**Comment by tokejepsen** [comment]
We can definitely do that:) We are currently revising the setup for more flexibility, think @mkolar has a pull-request coming next week.

**Comment by mkolar** [comment]
Yep. I'm almost done with the last tweaks, which will make it into simple but I think very flexible extension. Should be very easy to pick up too. I reckon writing a quick wiki shouldn't be a problem. It's just that I'm very on a off with coding time now because of workload we have here.

**Comment by mottosso** [comment]
That's great! Should we aim to get something mocked up sometime next week? Something rough but to the point.

I'll see if I can get us a demo-account for Pyblish too, both for users to try the integration out and also to get some tests going.

**Comment by tokejepsen** [comment]
We have the README about what happens for the old api and the new api.

Do we need anymore documentation at this point?

**Comment by mottosso** [comment]
No I think it looks good.

Next step would be to introduce a new user to pyblish-ftrack by pointing them to this documentation and see what questions come up.
