### ISSUE TITLE
Store object instead of dictionary

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#36]
Currently the extension is storing the ftrack data in a dictionary, but wouldn't it be better to store the objects themselves?

This would allow for less ftrack queries like `project = ftrack.Project(ftrack_data['Project']['id'])`

**Comment by mottosso** [comment]
Stick with plain-old-data.

I'll try and write something up on the topic next week, but for now, what you do currently with plain data in a dictionary is great. We can have a look at writing helper functions and such to simplify things, but the data stored must remain plain.

**Comment by mkolar** [comment]
I agree with @mottosso. The main point in doing dictionary was to simplify the amount of data that get's pulled from ftrack to a bare minimum. Btw with the new ftrack API every object will behave exactly like a plain dictionary so technically we'll eventually be just storing a subset of keys in identical way.

**Comment by mottosso** [comment]
Wrote a summary on the topic here, let me know if it makes sense.
- http://forums.pyblish.com/t/instances-and-plain-old-data/136/1
