### ISSUE TITLE
Simplify executable

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-ftrack#37]
Hey @tokejepsen, it struck me that I think most of [this](https://github.com/pyblish/pyblish-ftrack/blob/master/pyblish_ftrack/ftrack_event_plugin_path/pyblish_executable.py) can be simplified to this.

``` python
import pyblish_integration
pyblish_integration.setup()
pyblish_integration.show()
```

Not only is it shorter, but it will leverage the same already-running Pyblish QML as other hosts use.

**Comment by tokejepsen** [comment]
Probably, but won't look at this until I can run two hosts simultaneous:)

**Comment by mottosso** [comment]
Ah, yes it would be good to get that resolved.

I still can't replicate it here, it works fine on this side in several versions of Windows in a variety of configurations. :(

I've got a test we could run, a "deep clean" if you will. To be continued on the forums.
- http://forums.pyblish.com/t/publish-from-two-hosts-simultanous/126/32

**Comment by tokejepsen** [comment]
Do we want to have pyblish-ftrack use pyblish-standalone for the publish action?

How do we feel about cross extension dependencies?

**Comment by mottosso** [comment]
Sure, I think that sounds like a great idea.

Dependencies amongst Pyblish repositories is perfectly fine, just make a not of it in the installation instructions. To the end-user, it eventually won't make a difference, as they will be installing Pyblish as a whole, like we are with Pyblish for Windows currently, which will include all repositories.

**Comment by tokejepsen** [comment]
Guessing the best way would be to have the `pyblish.bat` on `PATH`, so it a simple `subprocess` launch?

**Comment by mottosso** [comment]
I'm thinking `pyblish.bat` will be reserved for the original command-line interface for Pyblish, and for `pyblish_standalone.bat` to be the executable for Pyblish Standalone.

Other than that, yes, having it on the path is possibly the most straightforward way possible, the problem might be with `python.bat` which might interfere with the original `python.exe`.

It's possible that it's a good idea _not_ to have a `python.bat` such that those binaries could always get added to the `PATH`.

Have a try, I think you can delete `python.bat`, but it's possible QML depends on it. See what works for you and I'll follow.

**Comment by tokejepsen** [comment]
We need to have pyblish-ftrack make use of pyblish-standalone, when launching directly from the browser. This also need to be documented, along with what `ftrack_event_plugin_path` directory is for.

**Comment by mottosso** [comment]
Is this still an issue?

**Comment by tokejepsen** [comment]
To be honest we haven't used the ftrack standalone publishing in quite a while, since getting a TV Paint integration working.
