### ISSUE TITLE
Multiple assets error raising

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#4]
When there are multiple assets to select from, there should be some kind of error raised as we can't assuming beyond one asset.

Since the current selector is collecting this data, my suggestion is to have a `assetsCount` data member which gets validated in a separate validator.

**Comment by mkolar** [comment]
How about instead of `assetCount` data member we actually add all the found assets on the task to `Assets` entry in ftrackData, that way we can check if there's more than one and fail validation if so, but could eventually use it for some good, like a dropdown list of existing assets if pyblish UI ever gets that far. Or run a validation that checks whether one of them matches 'preferred' name (potential user argument passed in selector) and if so let it publish to that, if not fail.

**Comment by mkolar** [comment]
Thinking about it some more, how about this?

We collect all assets from the task to `ftrackData['Assets']`

User can pass and optional data member in the selector just as he is doing with components now: `instance.data('ftrackAssetName')`

We run validation which:

``` python
# pseudo code
asset_to_use = None
assets = ftrackData['Assets']

if not assets :
     asset_to_use = ftrack.createNewAsset
else:
    # check if we know the expected asset name
    if instance.data('ftrackAssetName'):
        # Try to find asset with given name
        for asset in assets :
            if asset['name'] == instance.data('ftrackAssetName') :
                asset_to_use = ftrack.Asset(id=asset['id'])
                break
        # Create it if it wasn't found in existing assets
        if not asset_to_use:
            asset_to_use = ftrack.createNewAsset
    # In case user hasn't chosen preferred asset name
    else:
        # if there is exactly one asset and we don't have specified preferred name, use it
        if len(assets) == 1:
            asset_to_use = assets[0]
        # else raise an exception
        else:
            raise pyblish.api.ValidationError('Cannot figure out which asset to use')
```

 Unless I'm mistaken this should cover all possibilities for now. If user doesn't specify anything special, validation fails when it finds more assets, If he specified preferred name, it tries to find it and if it doesn't it creates it despite other assets already being present.

**Comment by tokejepsen** [comment]
> Thinking about it some more, how about this?

That sounds good to me:)

**Comment by tokejepsen** [comment]
This should be fixed in the latest update.
