### ISSUE TITLE
ftrack_api verbosity

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-ftrack#41]
### goal

the new ftrack is very **verbose** by default in pyblish. it can easly generate a half a Mb of log files and thats on a single instance.

to lower it's logging level.

``` python
logging.getLogger("ftrack_api").setLevel(logging.INFO)
logging.getLogger("requests").setLevel(logging.INFO)
```

**Comment by tokejepsen** [comment]
This has been added to the README :smile:
